schema_version = "1.0.0"

id = "Emanate_Studios_Tools"
version = "1.0.0"
name = "Emanate Studios by Emanuel Siu"
tagline = "Personal pipeline utilities"
maintainer = "Emanuel <you@example.com>"
type = "add-on"

blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]