import bpy

from ..helpers import bone_collections
from ..helpers import naming_unity as naming

NAMES = naming.register_tool(
    "org_bone_generator",
    label="generate ORG bones",
    owner=__name__,
    description="Creates ORG bones and assigns copy transform constraints to DEF bones",
)

# ------ Naming convention this tool works to ------------------------------
DEF_PREFIX = "DEF_"
ORG_PREFIX = "ORG_"

# Naming the constraint lets a second run recognise its own work instead of
# stacking a duplicate constraint on every DEF bone.
CONSTRAINT_NAME = "ORG Copy Transforms"
CONSTRAINT_TYPE = 'COPY_TRANSFORMS'

# Bone collections the two sets get sorted into.
DEFORM_COLLECTION = "DEFORMATION"
ORIGINAL_COLLECTION = "ORIGINAL"
# ---------------------------------------------------------------------------


def org_name_for(def_bone_name):
    """DEF_base -> ORG_base. Only the prefix changes; the rest is untouched."""
    return ORG_PREFIX + def_bone_name[len(DEF_PREFIX):]


def create_org_bones(armature_obj):
    """Mirror every DEF_ bone as an ORG_ bone. Must be called in EDIT mode.

    Returns (pairs, created, reused) where pairs is a list of
    (def_name, org_name) covering every DEF bone, whether or not its ORG
    counterpart had to be built this run.
    """
    edit_bones = armature_obj.data.edit_bones

    source_bones = [eb for eb in edit_bones if eb.name.startswith(DEF_PREFIX)]

    pairs = []
    created = []
    reused = []

    # --- pass one: create the bones -------------------------------------
    # Parenting is deferred to pass two because a bone's ORG parent may not
    # exist yet when the bone itself is created.
    for source in source_bones:
        org_name = org_name_for(source.name)
        pairs.append((source.name, org_name))

        if org_name in edit_bones:
            # Already generated by a previous run. Leave it as the user left
            # it -- overwriting would throw away any edits they made.
            reused.append(org_name)
            continue

        new_bone = edit_bones.new(org_name)
        new_bone.head = source.head
        new_bone.tail = source.tail
        new_bone.roll = source.roll
        new_bone.use_deform = False
        new_bone.inherit_scale = source.inherit_scale

        # Deliberately NOT copying the source bone's collection membership:
        # organize_bone_collections() below files this bone under ORIGINAL,
        # and inheriting DEF's membership would drag it into the hidden
        # DEFORMATION collection too.
        created.append(org_name)

    # --- pass two: rebuild the hierarchy --------------------------------
    def_to_org = dict(pairs)

    for def_name, org_name in pairs:
        if org_name not in created:
            continue

        source_parent = edit_bones[def_name].parent
        if source_parent is None:
            continue

        # A DEF parent maps to its ORG twin, so the ORG chain stands alone.
        # Any other parent (a control bone, say) is kept as-is, which is what
        # Blender's own duplicate does.
        parent_name = def_to_org.get(source_parent.name, source_parent.name)
        org_bone = edit_bones[org_name]
        org_bone.parent = edit_bones[parent_name]
        org_bone.use_connect = edit_bones[def_name].use_connect

    return pairs, created, reused


def organize_bone_collections(armature_obj, pairs):
    """File DEF bones under DEFORMATION (hidden) and ORG under ORIGINAL.

    Must be called in EDIT mode -- it works through edit_bones, which is the
    only view of the bones that is valid there.

    Returns a list of description strings.
    """
    armature = armature_obj.data
    changes = []

    deform, was_created = bone_collections.get_or_create_collection(armature, DEFORM_COLLECTION)
    if was_created:
        changes.append(f"created collection {DEFORM_COLLECTION}")
    moved = bone_collections.move_bones_to_collection(armature, [d for d, _ in pairs], deform)
    changes.append(f"{moved} bone(s) -> {DEFORM_COLLECTION} (hidden)")
    deform.is_visible = False

    original, was_created = bone_collections.get_or_create_collection(armature, ORIGINAL_COLLECTION)
    if was_created:
        changes.append(f"created collection {ORIGINAL_COLLECTION}")
    moved = bone_collections.move_bones_to_collection(armature, [o for _, o in pairs], original)
    changes.append(f"{moved} bone(s) -> {ORIGINAL_COLLECTION} (visible)")
    original.is_visible = True

    return changes


def add_copy_transforms(armature_obj, pairs):
    """Constrain each DEF bone to its ORG bone. Must be called in POSE mode.

    Returns (added, skipped) as lists of DEF bone names.
    """
    added = []
    skipped = []

    for def_name, org_name in pairs:
        pose_bone = armature_obj.pose.bones.get(def_name)
        if pose_bone is None:
            continue

        # Re-runs must not stack constraints. Match on what the constraint
        # does (type + target) rather than on its name, so a renamed one is
        # still recognised.
        already_there = any(
            con.type == CONSTRAINT_TYPE
            and con.target == armature_obj
            and con.subtarget == org_name
            for con in pose_bone.constraints
        )
        if already_there:
            skipped.append(def_name)
            continue

        constraint = pose_bone.constraints.new(CONSTRAINT_TYPE)
        constraint.name = CONSTRAINT_NAME
        constraint.target = armature_obj
        constraint.subtarget = org_name
        added.append(def_name)

    return added, skipped


class EMANATE_OT_org_bone_generator(bpy.types.Operator):

    bl_idname = NAMES.operator_idname
    bl_label = NAMES.label
    bl_description = NAMES.description
    bl_options = {'REGISTER', 'UNDO'}

    @classmethod
    def poll(cls, context):
        obj = context.active_object
        return obj is not None and obj.type == 'ARMATURE'

    def execute(self, context):
        armature_obj = context.active_object
        starting_mode = armature_obj.mode

        bpy.ops.object.mode_set(mode='EDIT')
        pairs, created, reused = create_org_bones(armature_obj)

        if not pairs:
            bpy.ops.object.mode_set(mode=starting_mode)
            self.report({'WARNING'}, f"No bones prefixed {DEF_PREFIX} on {armature_obj.name}")
            return {'CANCELLED'}

        # Still in edit mode, which is where collection membership has to be
        # set -- armature.bones is not valid until edit mode is left.
        collection_changes = organize_bone_collections(armature_obj, pairs)

        # Constraints live on pose bones, and pose bones for freshly created
        # edit bones only exist once edit mode has been left.
        bpy.ops.object.mode_set(mode='POSE')
        added, skipped = add_copy_transforms(armature_obj, pairs)

        bpy.ops.object.mode_set(mode=starting_mode)

        for def_name, org_name in pairs:
            print(f"[org-bones] {def_name} -> {org_name}")
        for change in collection_changes:
            print(f"[org-bones] {change}")

        self.report(
            {'INFO'},
            f"{len(created)} ORG bone(s) created, {len(reused)} reused; "
            f"{len(added)} constraint(s) added, {len(skipped)} already present"
        )
        return {'FINISHED'}


class EMANATE_PT_org_bone_generator(bpy.types.Panel):
    bl_idname = NAMES.panel_idname
    bl_label = NAMES.label
    bl_parent_id = naming.ROOT_PANEL_IDNAME
    bl_space_type = naming.SPACE_TYPE
    bl_region_type = naming.REGION_TYPE
    bl_options = {'DEFAULT_CLOSED'}
    bl_order = NAMES.order

    def draw(self, context):
        column = self.layout.column()

        obj = context.active_object
        if obj is None or obj.type != 'ARMATURE':
            column.label(text='- select an armature -')
            return


        column.operator(NAMES.operator_idname, text=f"Generate ORG Bones")


_classes = (EMANATE_OT_org_bone_generator, EMANATE_PT_org_bone_generator)


def register():
    naming.check_classes(_classes, NAMES)
    for cls in _classes:
        bpy.utils.register_class(cls)


def unregister():
    for cls in reversed(_classes):
        bpy.utils.unregister_class(cls)
